"""init models

Revision ID: 65fabc45e24c
Revises: d11372a51424
Create Date: 2025-09-21 13:08:14.891171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65fabc45e24c'
down_revision: Union[str, Sequence[str], None] = 'd11372a51424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toolkits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('employee_number', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('worker', 'manager', 'admin', name='roleenum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_number')
    )
    op.create_table('toolkit_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('toolkit_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['toolkit_id'], ['toolkits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('toolkit_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('give', 'take', name='typeenum'), nullable=True),
    sa.Column('transaction_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ok', 'manual_check', name='statusenum'), nullable=True),
    sa.ForeignKeyConstraint(['toolkit_id'], ['toolkits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('expected_qty', sa.Integer(), nullable=False),
    sa.Column('actual_qty', sa.Integer(), nullable=False),
    sa.Column('discrepancy', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_details')
    op.drop_table('qa_reports')
    op.drop_table('transactions')
    op.drop_table('toolkit_items')
    op.drop_table('users')
    op.drop_table('tools')
    op.drop_table('toolkits')
    # ### end Alembic commands ###
